(asdf:load-system :enhanced-thread-pool)
(in-package :enhanced-thread-pool)
(defvar *pool* (make-instance 'thread-pool :name "test" :min-size 1))
;(defvar *pool* (make-instance 'thread-pool :name "test" :min-size 2 :max-size nil))
;(defvar *pool* (make-instance 'thread-pool :name "test" :min-size 2 :max-size 3 :keep-alive-time 1))
;(defvar *pool* (make-instance 'thread-pool :name "test" :min-size 2 :max-size 204))
(start-pool *pool*)
(execute *pool*
         #'(lambda ()
             (sleep 3)
             (format t "Finished0~%")))
(format t "1~%")
(execute *pool*
         #'(lambda ()
             (sleep 3)
             (format t "Finished1~%")))
(format t "2~%")
(execute *pool*
         #'(lambda ()
             (sleep 3)
             (format t "Finished2~%")))
(format t "3~%")
(execute *pool*
         #'(lambda ()
             (sleep 3)
             (format t "Finished3~%")))
(format t "4~%")
(stop-pool *pool*)
(format t "5~%")

