;;; -*- lisp -*-

(in-package :ru.bazon.enhanced-thread-pool-tests)

(deftestsuite test-enhanced-thread-pool () ())

(defmacro thread-function (sleep-time lock result addition condition)
  (let ((addition-real addition))
    `(lambda ()
       (if ,condition
	   (error "Error in test")
	   (progn
	     (sleep ,sleep-time)
	     (bordeaux-threads:with-lock-held (,lock)
	       (incf ,result ,addition-real)))))))

(addtest
    test-simple-pooling
  (let ((threads-before-start (length (bordeaux-threads:all-threads)))
	(result 0)
	(lock (bordeaux-threads:make-lock))
	(thread-pool (make-instance 'thread-pool :name "test" :min-size 1)))
    (start-pool thread-pool)
    (execute thread-pool (thread-function 0 lock result 1 nil))
    (execute thread-pool (thread-function 0 lock result 2 nil))
    (sleep 0.5)
    (stop-pool thread-pool)
    (join-pool thread-pool)
    (sleep 2)
    (ensure-same 3 result :report "result")
    (ensure-same 0 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size")
    (ensure-same t (enhanced-thread-pool::empty-queue-p (slot-value thread-pool 'enhanced-thread-pool::idle-workers-queue)) :report "pool-empty")
    (ensure-same threads-before-start (length (bordeaux-threads:all-threads))) :report "threads"))

(addtest
    test-simple-pooling-condition
  (let ((threads-before-start (length (bordeaux-threads:all-threads)))
	(result 0)
	(lock (bordeaux-threads:make-lock))
	(thread-pool (make-instance 'thread-pool :name "test" :min-size 1)))
    (start-pool thread-pool)
    (execute thread-pool (thread-function 0 lock result 1 nil))
    (execute thread-pool (thread-function 0 lock result 1 t))
    (sleep 0.5)
    (stop-pool thread-pool)
    (join-pool thread-pool)
    (ensure-same 1 result)
    (ensure-same 0 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)))
    (ensure-same t (enhanced-thread-pool::empty-queue-p (slot-value thread-pool 'enhanced-thread-pool::idle-workers-queue)))
    (ensure-same threads-before-start (length (bordeaux-threads:all-threads)))))

(addtest
    test-fixed-thread-pooling
  (let ((threads-before-start (length (bordeaux-threads:all-threads)))
	(result 0)
	(lock (bordeaux-threads:make-lock))
	(thread-pool (make-fixed-thread-pool "test" :size 2)))
    (start-pool thread-pool)
    (sleep 0.2)
    (execute thread-pool (thread-function 2 lock result 1 nil))
    (execute thread-pool (thread-function 2 lock result 2 nil))
    (sleep 0.2)
    (execute thread-pool (thread-function 2 lock result 3 nil))
    (execute thread-pool (thread-function 2 lock result 4 nil))
    (sleep 2)
    (ensure-same 3 result :report "result-1")
    (ensure-same 2 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size-1")
    (stop-pool thread-pool)
    (join-pool thread-pool)
    (ensure-same 10 result :report "result-2")
    (ensure-same 0 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size-2")
    (ensure-same t (enhanced-thread-pool::empty-queue-p (slot-value thread-pool 'enhanced-thread-pool::idle-workers-queue)) :report "pool-empty")
    (ensure-same threads-before-start (length (bordeaux-threads:all-threads)) :report "threads")))

(addtest
    test-cached-thread-pooling
  (let ((threads-before-start (length (bordeaux-threads:all-threads)))
	(result 0)
	(lock (bordeaux-threads:make-lock))
	(thread-pool (make-cached-thread-pool "test" :size 2 :max-size 4 :keep-alive-time 1)))
    (start-pool thread-pool)
    (execute thread-pool (thread-function 2 lock result 1 nil))
    (execute thread-pool (thread-function 2 lock result 2 nil))
    (sleep 0.2)
    (execute thread-pool (thread-function 2 lock result 3 nil))
    (execute thread-pool (thread-function 2 lock result 4 nil))
    (execute thread-pool (thread-function 2 lock result 5 nil))
    (sleep 0.2)
    (ensure-same 4 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size-1")
    (sleep 2)
    (ensure-same 2 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size-2")
    (sleep 2)
    (ensure-same 2 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size-3")
    (stop-pool thread-pool)
    (join-pool thread-pool)
    (ensure-same 15 result :report "result")
    (ensure-same 0 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size-4")
    (ensure-same t (enhanced-thread-pool::empty-queue-p (slot-value thread-pool 'enhanced-thread-pool::idle-workers-queue)) :report "pool-empty")
    (ensure-same threads-before-start (length (bordeaux-threads:all-threads)) :report "threads")))

(addtest
    test-agressive-pooling
  (let ((threads-before-start (length (bordeaux-threads:all-threads)))
	(stress-size 1024)
	(result 0)
	(lock (bordeaux-threads:make-lock))
	(thread-pool (make-cached-thread-pool "test" :size 12 :max-size 16 :keep-alive-time 1)))
    (start-pool thread-pool)
    (iter (for i from 1 to stress-size)
	  (execute thread-pool (thread-function 0 lock result 1 nil)))
    (sleep 3)
    (stop-pool thread-pool)
    (join-pool thread-pool)
    (ensure-same stress-size result :report "result")
    (ensure-same 0 (enhanced-thread-pool::size (slot-value thread-pool 'enhanced-thread-pool::workers-set)) :report "workers-size")
    (ensure-same t (enhanced-thread-pool::empty-queue-p (slot-value thread-pool 'enhanced-thread-pool::idle-workers-queue)) :report "pool-empty")
    (ensure-same threads-before-start (length (bordeaux-threads:all-threads)) :report "threads")))
